name: q_chat_bot
description: "A customizable Flutter chatbot package with support for user and bot messages, rich UI elements, and suggestion handling for seamless interactions."
version: 1.0.5
homepage: https://github.com/el-kady3zzat/QBot-Package

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
